;; Install extensions if they're missing
(defun init--install-packages ()
  (packages-install
   '(ace-jump-buffer
     ace-jump-mode
     ace-window
     async
     autopair
     back-button
     button-lock
     cmake-mode
     cmake-project
     company
     company-c-headers
     company-cmake
     company-irony
     dash
     diminish
     dired+
     discover-my-major
     dpaste
     elpy
     epl
     expand-region
     f
     find-file-in-project
     fixmee
     flycheck
     flycheck-rust
     git-commit-mode
     git-rebase-mode
     go-eldoc
     go-mode
     helm
     helm-descbinds
     helm-projectile
     helm-swoop
     highlight-blocks
     highlight-escape-sequences
     highlight-indentation
     highlight-numbers
     hlinum
     ht
     htmlize
     idomenu
     imenu+
     irony
     kivy-mode
     ledger-mode
     lice
     list-utils
     magit
     makey
     monky
     monokai-theme
     multi-term
     multiple-cursors
     mustache
     nav-flash
     nlinum
     org
     org-page
     pandoc-mode
     parent-mode
     pcache
     persistent-soft
     pkg-info
     powerline
     pretty-mode
     pretty-mode-plus
     projectile
     py-autopep8
     pyvenv
     rainbow-mode
     relative-buffers
     rich-minority
     rust-mode
     s
     smart-mode-line
     smartrep
     string-utils
     ucs-utils
     visual-regexp
     visual-regexp-steroids
     web-beautify
     web-mode
     yaml-mode
     yasnippet)))

(condition-case nil
    (init--install-packages)
  (error
   (package-refresh-contents)
   (init--install-packages)))

