#+TITLE:   Configuraci贸n de GNU Emacs usando Doom
#+DATE:    enero 21, 2021
#+STARTUP: inlineimages nofold

#+begin_example
                                    
                 Actiones nostras tibi com铆timus, D贸mine,
                  ut ad maiorem gloriam tuam repleamur.
                                     
#+end_example

* Tabla de contenidos :TOC_3:noexport:
- [[#pre谩mbulo][Pre谩mbulo]]
- [[#configuraci贸n-por-defecto-sabor-jorge][Configuraci贸n por defecto, sabor Jorge]]
- [[#aspecto-visual-de-gnu-emacs][Aspecto visual de GNU Emacs]]
  - [[#tipograf铆a][tipograf铆a]]
  - [[#cambia-comportamiento-de-tab][cambia comportamiento de TAB]]
- [[#org][Org]]
  - [[#configuraci贸n-b谩sica][configuraci贸n b谩sica]]
  - [[#plantillas][plantillas]]
- [[#ispell][ispell]]
- [[#undo-y-redo][undo y redo]]
- [[#cierre-de-buffers][Cierre de buffers]]
- [[#iedit][iedit]]
- [[#yasnippets][yasnippets]]
- [[#golang][Golang]]
- [[#flutter-y-dart][Flutter y Dart]]
- [[#formateadores-de-c贸digo][formateadores de c贸digo]]
- [[#detecci贸n-de-sangrado][Detecci贸n de sangrado]]
  - [[#apaga-auto-sangrado-en-web-mode][Apaga auto-sangrado en web-mode]]
- [[#tree-sitter][tree-sitter]]
- [[#correo-electr贸nico][correo electr贸nico]]
- [[#tramp][tramp]]
- [[#nginx][Nginx]]
- [[#configuraci贸n-de-depuraci贸n-con-dap-mode][configuraci贸n de depuraci贸n con dap-mode]]

* Pre谩mbulo
Datos personales y opciones de Emacs lisp.
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-

(setq user-full-name "Jorge Araya Navarro"
      user-mail-address "jorge@esavara.cr")
#+end_src
* Configuraci贸n por defecto, sabor Jorge
Hay comportamientos en Emacs que me gustar铆a que fueran usados en Doom, y que se pueda activar como una bandera en =:config default=, los defino aqu铆.
#+begin_src emacs-lisp
(when (featurep! :config default +jorge)
  ;; activa electric-pair-mode solo si +smartparens no lo esta
  (unless (featurep! :config default +smartparens)
    (add-hook! 'prog-mode-hook #'electric-pair-local-mode)
    (add-hook! 'prog-mode-hook #'turn-off-smartparens-mode))
  (after! highlight-escape-sequences
    (add-hook! 'prog-mode-hook #'turn-on-hes-mode))
  (after! uniquify
    (setq uniquify-buffer-name-style 'forward)))

;; cambia ubicacion de snippets para YaSnippet
(setf +snippets-dir (expand-file-name "plantillas" doom-private-dir))
#+end_src
* Aspecto visual de GNU Emacs
#+begin_src emacs-lisp
(setq doom-theme 'doom-gruvbox)
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(after! doom-modeline
  (setq doom-modeline-persp-name t))

(setq display-line-numbers-type t)

(setq fancy-splash-image (expand-file-name "dashboard/JHS.png" doom-private-dir))
;; TODO: cambiar arte ASCII

(setq all-the-icons-scale-factor 0.8)

(custom-set-faces!
  '(aw-leading-char-face
    :foreground "white" :background "red"
    :weight bold :height 2.5 :box (:line-width 10 :color "red")))
#+end_src
** tipograf铆a
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Fira Code" :size 16)
      doom-big-font (font-spec :family "Fira Code" :size 26))
#+end_src
** cambia comportamiento de TAB
No estoy interesado en insertar un tabulador al presionar TAB.
#+begin_src emacs-lisp
(setq tab-always-indent t)
#+end_src
* Org
** configuraci贸n b谩sica
#+begin_src emacs-lisp
(setq org-directory "~/org/")
(setq org-agenda-files (expand-file-name ".agendas" doom-private-dir))
(setq org-refile-targets `((nil :maxlevel . 9)
                           (org-agenda-files :maxlevel . 9)
                           (org-default-notes-file :maxlevel . 9)
                           (,(expand-file-name "quizas.org" org-directory) :maxlevel . 9)))
#+end_src
** plantillas
#+begin_src emacs-lisp
(after! org
  (setq org-todo-keywords
        '((sequence "POR-HACER(p)" "SIGNT(s)" "|" "TERMINADO(t)")
          (sequence "ESPERA(e@/!)" "RETENER(r@/!)" "|" "CANCELADO(c@/!)")))
  (setq org-todo-keyword-faces
        '(("POR-HACER" :foreground "red" :weight bold)
          ("SIGNT" :foreground "blue" :weight bold)
          ("TERMINADO" :foreground "forest green" :weight bold)
          ("ESPERA" :foreground "orange" :weight bold)
          ("RETENER" :foreground "magenta" :weight bold)
          ("CANCELADO" :foreground "forest green" :weight bold)))
  (setq org-agenda-custom-commands
        '(("a" "Agenda"
           ((tags "PRIORITY=\"A\""
                  ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                   (org-agenda-overriding-header "Tareas de alta prioridad por terminar:")))
            (agenda ""
                    ((org-agenda-span 'day)
                     (org-agenda-overriding-header "Hoy:")
                     (org-agenda-show-all-dates nil)))
            (agenda ""
                    ((org-agenda-span 'week)
                     (org-agenda-start-day "+1d") ;; A partir de ma帽ana
                     (org-agenda-overriding-header "Semana:")
                     (org-agenda-show-all-dates nil)))
            (agenda ""
                    ((org-agenda-span 'month)
                     ;; A partir de la siguiente semana
                     (org-agenda-start-day "+1w")
                     (org-agenda-overriding-header "Mes:")
                     (org-agenda-show-all-dates nil)))
            (alltodo ""
                     ((org-agenda-skip-function
                       '(and
                         (org-agenda-skip-if nil '(scheduled deadline))))
                      (org-agenda-overriding-header "Todas las tareas de prioridad normal:"))))))))

(after! org-capture
  (setq org-plantillas-directory (expand-file-name "org-plantillas" doom-private-dir))
  (setq org-default-notes-file (expand-file-name "notas.org" org-directory))
  (setq org-capture-templates `(("T" "Anotacion t茅cnica" entry (file "apuntes tecnicos.org")
                                 (file ,(expand-file-name "anotacion tecnica.orgcaptmpl" org-plantillas-directory))
                                 :kill-buffer t :clock-in t :clock-resume t)))
  (add-to-list 'org-capture-templates `("t" "Tarea por hacer" entry (file "cosas por hacer.org")
                                        (file ,(expand-file-name "tareas por hacer.orgcaptmpl" org-plantillas-directory))
                                        :kill-buffer t :clock-in t :clock-resume t) :append)
  (add-to-list 'org-capture-templates `("c" "Agregar al calendario" entry (file "agenda.org")
                                        (file ,(expand-file-name "tareas por hacer.orgcaptmpl" org-plantillas-directory))
                                        :kill-buffer t :clock-in t :clock-resume t) :append)
  (add-to-list 'org-capture-templates `("n" "Notas" entry (file+headline org-default-notes-file "Reorganizar")
                                        (file ,(expand-file-name "notas.orgcaptmpl" org-plantillas-directory))
                                        :kill-buffer t :clock-in t :clock-resume t) :append)
  (add-to-list 'org-capture-templates `("f" "Fechas o eventos" entry (file+headline "cosas por hacer.org" "Fechas")
                                        (file ,(expand-file-name "fecha o evento.orgcaptmpl" org-plantillas-directory))
                                        :kill-buffer t :clock-in t :clock-resume t) :append)
  (add-to-list 'org-capture-templates `("r" "Receta de cocina" entry (file "recetas.org")
                                        (file ,(expand-file-name "recetas.orgcaptmpl" org-plantillas-directory))
                                        :kill-buffer t :clock-in t :clock-resume t) :append)
  (add-to-list 'org-capture-templates `("P" "Protocol" entry (file+headline org-default-notes-file "Reorganizar")
                                        (file ,(expand-file-name "protocol.orgcaptmpl" org-plantillas-directory))
                                        :kill-buffer t :clock-in t :clock-resume t) :append)
  (add-to-list 'org-capture-templates `("l" "Protocol Link" entry (file+headline org-default-notes-file "Reorganizar")
                                        (file ,(expand-file-name "protocol.orgcaptmpl" org-plantillas-directory))
                                        :kill-buffer t :clock-in t :clock-resume t) :append)
  ;; Ajuste para LaTeX
  (add-to-list 'org-latex-packages-alist '("" "gchords" t)))
#+end_src
* ispell
Con base al blog post [[https://200ok.ch/posts/2020-08-22_setting_up_spell_checking_with_multiple_dictionaries.html][Setting up spell checking with multiple dictionaries in Emacs]] activamos varios idiomas a la vez.
#+begin_src emacs-lisp
(after! ispell
  (setq ispell-program-name "hunspell")
  (setq ispell-dictionary "es_CR,en_US")
  (ispell-set-spellchecker-params)
  (ispell-hunspell-add-multi-dic "es_CR,en_US")
  (setq ispell-personal-dictionary "~/.hunspell_personal")
  (unless (file-exists-p ispell-personal-dictionary)
    (write-region "" nil ispell-personal-dictionary nil 0)))
#+end_src
* undo y redo
cambia atajos para llamar a undo y redo
#+begin_src emacs-lisp
(map! "C-z" #'undo)
(map! "C-S-z" #'undo-fu-only-redo)
#+end_src
* Cierre de buffers
Cambia atajo para matar el buffer actual
#+begin_src emacs-lisp
(unbind-key "C-x k" global-map)
(map! "C-x k" #'kill-this-buffer)
#+end_src
* iedit
Realiza ajustes peque帽os para iedit-mode
#+begin_src emacs-lisp
(map! "C-M-;" #'iedit-mode)
(map! :map iedit-mode-keymap "RET" #'iedit--quit)
#+end_src
* yasnippets
Configura yasnippet y modifica todos los backends de company-mode para incluirlo en los resultados
#+begin_src emacs-lisp
(when (and (featurep! :completion company)
           (featurep! :editor snippets)
           (featurep! :tools lsp))

  (defun shackra-use-company-capf-with-yasnippet ()
    (setq company-backends '((company-capf company-yasnippet))))

  (add-hook! 'company-mode-hook #'shackra-use-company-capf-with-yasnippet))

(after! yasnippet
  (add-to-list 'yas-snippet-dirs (expand-file-name "plantillas" doom-private-dir) nil))
#+end_src
* Golang
Ajustes menores para Golang
#+begin_src emacs-lisp
(after! go-mode
  (setq-default gofmt-command "goimports"))
#+end_src
* Flutter y Dart
ajustes menores para estos modos mayores
#+begin_src emacs-lisp
(after! dart-mode
  (setq-default lsp-dart-sdk-dir nil)
  (setq-default flutter-sdk-path nil))
#+end_src
* formateadores de c贸digo
Define mis propios reformateadores de c贸digo fuente usando [[https://github.com/raxod502/apheleia][apheleia]].
#+begin_src emacs-lisp
(when (featurep! :editor reformat)
  (after! apheleia
    (require 'apheleia)
    ;; activa globalmente alpheleia
    (apheleia-global-mode)))

(after! apheleia-mode
  ;; TODO: agregar rustywind cuando
  ;; https://github.com/raxod502/apheleia/issues/31 haya sido resuelto
  (add-to-list 'apheleia-formatters '(rustywind . ("rustywind" "--stdin")))
  (add-to-list 'apheleia-mode-alist '(typescript-tsx-mode . prettier)))
#+end_src
* Detecci贸n de sangrado
Con =dtrt-indent-mode= Emacs puede detectar autom谩ticamente el nivel de sangrado en archivos de c贸digo fuente en varios lenguajes de programaci贸n.
** Apaga auto-sangrado en web-mode
#+begin_src emacs-lisp
(after! web-mode
  (setq-default web-mode-enable-auto-indentation nil))
#+end_src
* tree-sitter
Mejor y veloz resaltado de c贸digo fuente
#+begin_src emacs-lisp
(when (featurep! :ui tree-sitter)
  (after! tree-sitter
    (require 'tree-sitter-langs)
    (require 'tree-sitter-debug)
    (require 'tree-sitter-query)
    (global-tree-sitter-mode)
    (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)))
#+end_src
* correo electr贸nico
#+BEGIN_SRC emacs-lisp :tangle no
(after! mu4e
  (setq +mu43-mu4e-mail-path "~/mail")
  (set-email-account! "jorge@esavara.cr"
                      '((mu4e-sent-folder       . "/personal/Sent Mail")
                        (mu4e-drafts-folder     . "/personal/Drafts")
                        (mu4e-trash-folder      . "/personal/Trash")
                        (mu4e-refile-folder     . "/personal/All Mail")
                        (smtpmail-smtp-user     . "jorge@esavara.cr")
                        (mu4e-compose-signature . "---\nJorge"))
                      t)
  (set-email-account! "jaraya@kue-cr.com"
                      '((mu4e-sent-folder       . "/kue/Sent")
                        (mu4e-drafts-folder     . "/kue/Drafts")
                        (mu4e-trash-folder      . "/kue/Trash")
                        (mu4e-refile-folder     . "/kue/All Mail")
                        (smtpmail-smtp-user     . "jaraya@kue-cr.com")
                        (mu4e-compose-signature . "---\nJorge Araya"))
                      nil))
#+END_SRC
* tramp
Ajustes para Tramp (sacados de [[https://tecosaur.github.io/emacs-config/config.html#tramp][Doom Emacs Configuration]])
#+begin_src emacs-lisp
(after! tramp
  (setenv "SHELL" "/bin/bash"))
#+end_src
* Nginx
Modo mayor para configurar archivos asociados a Nginx
#+begin_src emacs-lisp
(when (featurep! :lang nginx)
  (after! nginx-mode
    (require 'nginx-mode)))
#+end_src
* configuraci贸n de depuraci贸n con dap-mode
#+begin_src emacs-lisp
(after! dap-mode
  ;; configura dap-mode para depurar en Chrome/Brave
  (require 'dap-chrome)
  (dap-chrome-setup))
#+end_src
