---
- name: Instala Emacs 28 en MacOS
  hosts: localhost
  connection: local

  tasks:
    - name: Agrega fuentes para emacs-plus
      community.general.homebrew_tap:
        name: d12frosted/emacs-plus
        state: present
    - name: Instala Emacs 28
      community.general.homebrew:
        name: emacs-plus@28
        state: latest
        update_homebrew: yes
        install_options: with-dbus,with-xwidgets,with-modern-cg433n-icon
    - name: Elimina Emacs.app
      file:
        state: absent
        path: /Application/Emacs.app
    - name: Copia Emacs.app desde emacs-plus a /Applications
      copy:
        src: /usr/local/opt/emacs-plus@28/Emacs.app
        dest: /Applications
        mode: preserve
